version: '3.8'

networks:
  cassandra:

services:
  cass1:
    image: cassandra:4.1.0
    container_name: cass1
    hostname: cass1
    mem_limit: ${CASSANDRA_MEM_LIMIT}
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./c1_data:/var/lib/cassandra
      - ./c1_cfg:/etc/cassandra
    environment: &environment
        CASSANDRA_SEEDS: "cass1,cass2"
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
  cass2:
    image: cassandra:4.1.0
    container_name: cass2
    hostname: cass2
    mem_limit: ${CASSANDRA_MEM_LIMIT}
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - ./c2_data:/var/lib/cassandra
      - ./c2_cfg:/etc/cassandra
    environment: *environment
    depends_on:
      cass1:
        condition: service_healthy
  cass3:
    image: cassandra:4.1.0
    container_name: cass3
    hostname: cass3
    mem_limit: ${CASSANDRA_MEM_LIMIT}
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - ./c3_data:/var/lib/cassandra
      - ./c3_cfg:/etc/cassandra
    environment: *environment
    depends_on:
      cass2:
        condition: service_healthy
